# Server port
server.port=8080

#openapi
springdoc.show-actuator-false
springdoc.packages-to-scan=com.company.device.device
springdoc.api-docs.path=/api-docs

# Datasource connection-mysql
#spring.datasource.platform=mysql
#spring.datasource.initialization-mode=always
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.application.name=device
#spring.jpa.show-sql=true
#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/device
#spring.datasource.username=root
#spring.datasource.password=password

# Datasource connection-h2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true

# Logging
logging.level.org.springframework=ERROR
logging.level.com.numericaideas=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


