package com.company.device.device.mapper;

import com.company.device.device.autogenerated.dto.DeviceCreateRequestDto;
import com.company.device.device.autogenerated.dto.DeviceDto;
import com.company.device.device.autogenerated.dto.StateDto;
import com.company.device.device.domain.Device;
import com.company.device.device.domain.enums.State;
import org.mapstruct.InjectionStrategy;
import org.mapstruct.Mapper;

import org.mapstruct.Mapping;
import org.springframework.stereotype.Component;


import java.util.List;

@Mapper(componentModel = "spring")
@Component
public abstract class DeviceMapper {
	public abstract List<DeviceDto> toListDto(List<Device> devices);
	public abstract DeviceDto toDto(Device device);
	public abstract Device toEntity(DeviceDto deviceDto);
	public abstract State toState(StateDto stateDto);

	// DTO -> Entity
	@Mapping(target = "id", ignore = true) // id generated by DB/service
	@Mapping(target = "state", source = "state", qualifiedByName = "toState")
	public abstract Device toEntity(DeviceCreateRequestDto dto);

}
